FROM golang:1.8.2

RUN mkdir -p /opt/kubeflow
RUN mkdir -p /opt/kubeflow/test
COPY mxnet-operator.v2 /opt/kubeflow
RUN chmod a+x /opt/kubeflow/mxnet-operator.v2

CMD ["/opt/kubeflow/mxnet-operator.v2", "--alsologtostderr", "-v=1"]
