apiVersion: apps/v1
kind: Deployment
metadata:
  name: mx-job-operator
  labels:
    name: mx-job-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mx-job-operator
  template:
    metadata:
      labels:
        name: mx-job-operator
    spec:
      containers:
      - name: mx-job-operator
        image: mxjob/mxnet-operator:v2-test-3
        imagePullPolicy: Always
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
